# ------------------------------------ #
#     ServerSelector Configuration     #
# ------------------------------------ #

# ------------------------------------ #
#            Main menu item            #
# ------------------------------------ #

# Whether the selector item is enabled or not
# If set to true the selector item will be put in your inventory at the given slot once you join (regardless of what item is currently at that slot)
selector-enabled: true
# The item of the selector (id's are not supported)
# Use https://www.digminecraft.com/lists/item_id_list_pc.php for a list of 1.15.2 materials
selector-item: "COMPASS"
# The display name of the selector item in your inventory
selector-name: "&3&lServer Selector"
# The slot to put your selector item in (if enabled), start counting at 0
selector-slot: 4

# If set to true you can move the item around in your inventory
selector-move: false
# If set to true you can drop the selector item
selector-drop: false


# ------------------------------------ #
#            Server Pinging            #
# ------------------------------------ #

# All values listed below are treated as seconds
# Important to note is that the queue will be processed by the bungeecord server

# How long the server waits before updating their information
# This information includes; status (whitelist/online), player capacity, max players
update-delay: 10

# How long the server waits before fetching any new information the bungee got from other servers
fetch-delay: 10